
development:
  adapter: mysql2
  database: <%= CONFIG[:adminportal_development_database] %>
  username: <%= CONFIG[:adminportal_development_username] %>
  password: <%= CONFIG[:adminportal_development_password] %>
  host: <%= CONFIG[:adminportal_development_server] %>
  port: <%= CONFIG[:adminportal_development_port] %>
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: <%= CONFIG[:adminportal_test_database] %>
  username: <%= CONFIG[:adminportal_test_username] %>
  password: <%= CONFIG[:adminportal_test_password] %>
  host: <%= CONFIG[:adminportal_test_server] %>
  port: <%= CONFIG[:adminportal_test_port] %>
  encoding: utf8
  pool: 5
  timeout: 5000
